### ISSUE TITLE
Changes to query protocol in TF2 servers after update at 16.09.2021

### ISSUE THREAD

**Issue by monsterbnd** [multiplay/qstat#107]
qstat 2.15 and 2.16.
I have no responce from my tf2 servers after update at 16.09.2021.
qstat -retry 1 -nh -a2s XXXX:XXXXX
XXXX:XXXXX no response
I think now a challenge is required: https://steamcommunity.com/discussions/forum/14/2974028351344359625/

qstat -retry 1 -d -d -d -a2s 37.230.228.219:27242
ADDRESS           PLAYERS      MAP   RESPONSE TIME    NAME
debug(1) 17:02:53 qstat.c:4543 bind_qserver2() - start 0x55cf8c372110 @ 37.230.228.219:27242
debug(1) 17:02:53 qstat.c:4694 bind_sockets() - send 37.230.228.219:27242
debug(2) 17:02:53 qstat.c:4703 bind_sockets() - calling status_query_func for 0x55cf8c372110 - connect
debug(2) 17:02:53 qserver.c:33 qserver_send_initial() - [A2S] send
debug(3) 17:02:53 qstat.c:4778 process_func_ret() - 0x55cf8c372110, 0
debug(3) 17:02:53 qstat.c:4815 send_packets() - processing...
debug(2) 17:02:53 qstat.c:3122 do_work() - connected: 1
debug(2) 17:02:53 qstat.c:5745 qserver_get_timeout() - timeout for 0x55cf8c372110 is diff1 1000 diff2 65535
debug(2) 17:02:53 qstat.c:3142 do_work() - rc 1
debug(2) 17:02:53 qstat.c:3165 do_work() - recvfrom: 9
debug(1) 17:02:53 qstat.c:3179 do_work() - recv   7   7 37.230.228.219:27242
debug(2) 17:02:53 qstat.c:3196 do_work() - fill: 1 < 40
FROM 37.230.228.219:27242 len 9
    0: ffffffff 417806e7 2b                 ....Ax.. +

debug(2) 17:02:53 qstat.c:3247 do_work() - connected, pre-packet_func: 1
debug(2) 17:02:53 a2s.c:233 deal_with_a2s_packet() - A2S type = 41
debug(3) 17:02:53 a2s.c:248 deal_with_a2s_packet() - challenge 2be70678
debug(3) 17:02:53 qstat.c:4778 process_func_ret() - 0x55cf8c372110, 1
debug(3) 17:02:53 qstat.c:5662 cleanup_qserver() - cleanup_qserver 0x55cf8c372110, 0
debug(3) 17:02:53 qstat.c:5664 cleanup_qserver() - server has no name, forcing close
debug(3) 17:02:53 qstat.c:5680 cleanup_qserver() - close_it 1
37.230.228.219:27242 no response
debug(2) 17:02:53 qstat.c:3249 do_work() - connected, post-packet_func: 0
debug(3) 17:02:53 qstat.c:4815 send_packets() - processing...
debug(3) 17:02:53 qstat.c:4926 send_packets() - done
debug(2) 17:02:53 qstat.c:3263 do_work() - connected: 0

**Comment by stevenh** [comment]
Can you test #109 to make sure that works for you please @monsterbnd?

**Comment by monsterbnd** [comment]
yes, it works.
qstat -retry 1 -a2s 37.230.228.219:27242
ADDRESS           PLAYERS      MAP   RESPONSE TIME    NAME
37.230.228.219:27242   6/33  0/0  koth_harvest_final     13 / 0  tf [ G44.ROCKS ] [All Popular Maps]
