### ISSUE TITLE
qstat command not found on debian-arm64

### ISSUE THREAD

**Issue by JTinkers** [multiplay/qstat#108]
Package installed via `sudo apt install qstat`
Installed succesfully, but `qstat` returns `command not found`

`which qstat` yields empty line.

`find ./ -name "qstat"` finds
`./usr/share/doc/qstat
./usr/share/lintian/overrides/qstat`

So, clearly it must be installed - right?

**Comment by illwieckz** [comment]
On Debian, the binary is named [`quakestat`](https://packages.debian.org/bullseye/arm64/qstat/filelist), probably because the `qstat` name seems to already be taken by [something else](`https://manpages.debian.org/buster/gridengine-client/qstat.1.en.html`).

**Comment by JTinkers** [comment]
I've just downloaded it for linux-x64 and ran it with box64, a bit less hassle.

**Comment by stevenh** [comment]
Thanks for the answer @illwieckz, seems something we can't do anything about, so gonna close this.
