### ISSUE TITLE
Provided a macOS binary

### ISSUE THREAD

**Issue by shamilovtim** [multiplay/qstat#112]
Binary built at 68f2d38
[qstatmacOS.zip](https://github.com/multiplay/qstat/files/7231773/qstatmacOS.zip)

**Comment by stevenh** [comment]
Thanks @shamilovtim happy to accept a PR to update the release github action to also build a macos binary.

**Comment by lwaddicor** [comment]
https://github.com/multiplay/qstat/commit/fab391255297c437fb84676104508a8b489fa8bf which adds this has been merged and released under https://github.com/multiplay/qstat/releases/tag/v2.17

There should be an osx binary now included on all future releases :+1:

**Comment by shamilovtim** [comment]
Awesome, thank you so much!
