### ISSUE TITLE
Cleaning the source code

### ISSUE THREAD

**Issue by illwieckz** [multiplay/qstat#14]
Hi, the current code is very old so it's naturally messy and do not follow coherent guidelines. 

For example code indentation use 4-spaces per level, but comment indentation use tab and sometime tab are expected to be 4-space long and sometime 8-space long.

There is a new guideline for code: https://www.freebsd.org/cgi/man.cgi?query=style&sektion=9
But the current code does not follow them yet.

Also, it could be very good to split the too-big `qstat.c` and `qstat.h` files, and perhaps some directory structures to store them, currently all is stored on the repository root directory, why not a `src/` directory?

Nobody loves whitespace commit, but every one loves good-looking code, since `qstat` is not very forked yet, it's the good time to do it, no?

**Comment by stevenh** [comment]
A white space cleanup would be good. Personally I don't have time ATM, but I'm totally willing to accept a pull to achieve that.
