### ISSUE TITLE
Can't Query TeamSpeak 3 Server

### ISSUE THREAD

**Issue by Xylemon** [multiplay/qstat#35]
Hello, I'm trying my best to figure out how to query a TS3 server, but not matter what I do I keep getting this error message:

qstat -pa -ts3 servers.bloodbathsoftworks.com:9987
option flag missing for server type "-ts3"

I know it says option flags are missing but I've tried several different ones and still get the message. Is there an example of what I should be doing? I didn't seen anything regarding TeamSpeak servers in the html doc.

**Comment by stevenh** [comment]
You need to specify the username and password options to query ts3 servers e.g.
```shell
qstat -ts3,allservers=1,username=<admin_name>,password=<admin_password> <ip>:<port>
```

**Comment by Xylemon** [comment]
Thank you for the reply, is there a way to query a TS3 server without providing any login info? I just want to crawl simple online status and amount of people on the server.

**Comment by Xylemon** [comment]
So I've tried my server with the query protocol on TS3 and using my Admin ServerQuery login and still got a "no response" message.

qstat -ts3,allservers=1,username=adminhere,password=passwordhere servers.bloodbathsoftworks.com:10011

**Comment by Xylemon** [comment]
I am still getting a "no response" message, any help?

**Comment by stevenh** [comment]
Blocked port?

**Comment by Xylemon** [comment]
The port seems to be fine, in fact I'm pretty sure that's how GameTracker crawls info from my TS3 server. GT seems to act as a GuestQuery to crawl information, could it somehow be interfering with QStat's querying?

**Comment by stevenh** [comment]
Try with the -d -d -d -d and see if that makes it clear what's happening

**Comment by Xylemon** [comment]
Trying it with "guest" spits out this:

qstat -ts3,allservers=1,username=guest,nopassword servers.bloodbathsoftworks.com:10011 -d -d -d -d
debug(4) 07:34:52 qstat.c:4164 add_qserver() - servers.bloodbathsoftworks.com:10011, ts3, (null), allservers=1,username=guest,nopassword
debug(1) 07:34:52 hcache.c:365 hcache_lookup_hostname() - looking up servers.bloodbathsoftworks.com
debug(2) 07:34:52 hcache.c:375 hcache_lookup_hostname() - validating servers.bloodbathsoftworks.com
debug(2) 07:34:52 hcache.c:380 hcache_lookup_hostname() - returning 4403fb8c
ADDRESS           PLAYERS      MAP   RESPONSE TIME    NAME
debug(1) 07:34:52 qstat.c:4860 bind_qserver2() - start 0x85db40 @ 68.3.251.140:10011
debug(2) 07:34:52 qstat.c:4958 bind_qserver2() - connect:68.3.251.140:10011 - in progress
debug(2) 07:34:52 qstat.c:5095 bind_sockets() - calling status_query_func for 0x85db40 - in progress
debug(3) 07:34:52 ts3.c:162 send_ts3_request_packet() - send_ts3_request_packet: state = 0
debug(3) 07:34:52 qstat.c:5128 process_func_ret() - 0x85db40, 0
debug(3) 07:34:52 qstat.c:5164 send_packets() - processing...
debug(2) 07:34:52 qstat.c:3130 do_work() - connected: 1
debug(2) 07:34:52 qstat.c:6246 qserver_get_timeout() - timeout for 0x85db40 is diff1 500 diff2 65535
debug(2) 07:34:52 qstat.c:3153 do_work() - rc 1
debug(2) 07:34:52 qstat.c:3181 do_work() - recvfrom: 5
debug(1) 07:34:52 qstat.c:3207 do_work() - recv   9   9 68.3.251.140:10011
debug(2) 07:34:52 qstat.c:3216 do_work() - fill: 1 < 40
FROM servers.bloodbathsoftworks.com:10011 len 5
    0: 5453330a 0d                          TS3..

debug(2) 07:34:52 qstat.c:3275 do_work() - connected, pre-packet_func: 1
debug(2) 07:34:52 ts3.c:213 deal_with_ts3_packet() - processing...
debug(3) 07:34:52 ts3.c:227 deal_with_ts3_packet() - packet: combined = 0, challenge = 0, n_servers = 999
debug(4) 07:34:52 packet_manip.c:182 add_packet() - first packet: 0 id, 0 index, 1 max, 1 calc_max
debug(4) 07:34:52 packet_manip.c:42 combine_packets() - max:1, id:0
debug(4) 07:34:52 packet_manip.c:143 combine_packets() - callback
FROM servers.bloodbathsoftworks.com:10011 len 5
    0: 5453330a 0d                          TS3..

debug(2) 07:34:52 ts3.c:213 deal_with_ts3_packet() - processing...
debug(3) 07:34:52 ts3.c:227 deal_with_ts3_packet() - packet: combined = 1, challenge = 0, n_servers = 999
debug(2) 07:34:52 ts3.c:262 deal_with_ts3_packet() - combined packet: valid_response: 1, challenge: 0, n_servers: 999, offset: 3
debug(3) 07:34:52 ts3.c:162 send_ts3_request_packet() - send_ts3_request_packet: state = 1
debug(2) 07:34:52 qserver.c:142 send_packet() - [TS3] send
TO servers.bloodbathsoftworks.com:10011 len 12
    0: 73657276 65726c69 73740d0a           serverli st..

debug(3) 07:34:52 qstat.c:5128 process_func_ret() - 0x85db40, 0
debug(2) 07:34:52 qstat.c:3277 do_work() - connected, post-packet_func: 1
debug(3) 07:34:52 qstat.c:5164 send_packets() - processing...
debug(2) 07:34:52 qstat.c:5207 send_packets() - server 0x85db40, name (null), retry1 2, next_rule (nil), next_player_info 65535, num_players 0, n_retries 3
debug(3) 07:34:52 qstat.c:5300 send_packets() - done
debug(2) 07:34:52 qstat.c:3293 do_work() - connected: 1
debug(2) 07:34:52 qstat.c:6246 qserver_get_timeout() - timeout for 0x85db40 is diff1 1000 diff2 65535
debug(2) 07:34:52 qstat.c:3153 do_work() - rc 1
debug(2) 07:34:52 qstat.c:3181 do_work() - recvfrom: 146
debug(1) 07:34:52 qstat.c:3207 do_work() - recv   9   0 68.3.251.140:10011
debug(2) 07:34:52 qstat.c:3216 do_work() - fill: 1 < 40
FROM servers.bloodbathsoftworks.com:10011 len 146
    0: 57656c63 6f6d6520 746f2074 68652054  Welcome  to the T
   16: 65616d53 7065616b 20332053 65727665  eamSpeak  3 Serve
   32: 72517565 72792069 6e746572 66616365  rQuery i nterface
   48: 2c207479 70652022 68656c70 2220666f  , type " help" fo
   64: 72206120 6c697374 206f6620 636f6d6d  r a list  of comm
   80: 616e6473 20616e64 20226865 6c70203c  ands and  "help <
   96: 636f6d6d 616e643e 2220666f 7220696e  command> " for in
  112: 666f726d 6174696f 6e206f6e 20612073  formatio n on a s
  128: 70656369 66696320 636f6d6d 616e642e  pecific  command.
  144: 0a0d                                 ..

debug(2) 07:34:52 qstat.c:3275 do_work() - connected, pre-packet_func: 1
debug(2) 07:34:52 ts3.c:213 deal_with_ts3_packet() - processing...
debug(3) 07:34:52 ts3.c:227 deal_with_ts3_packet() - packet: combined = 0, challenge = 2, n_servers = 3
debug(4) 07:34:52 packet_manip.c:187 add_packet() - another packet: 0 id, 1 index, 2 max, 1 calc_max
debug(4) 07:34:52 packet_manip.c:206 add_packet() - calced max = 2
debug(4) 07:34:52 packet_manip.c:42 combine_packets() - max:2, id:0
debug(4) 07:34:52 packet_manip.c:42 combine_packets() - max:2, id:0
debug(4) 07:34:52 packet_manip.c:143 combine_packets() - callback
FROM servers.bloodbathsoftworks.com:10011 len 151
    0: 5453330a 0d57656c 636f6d65 20746f20  TS3..Wel come to 
   16: 74686520 5465616d 53706561 6b203320  the Team Speak 3 
   32: 53657276 65725175 65727920 696e7465  ServerQu ery inte
   48: 72666163 652c2074 79706520 2268656c  rface, t ype "hel
   64: 70222066 6f722061 206c6973 74206f66  p" for a  list of
   80: 20636f6d 6d616e64 7320616e 64202268   command s and "h
   96: 656c7020 3c636f6d 6d616e64 3e222066  elp <com mand>" f
  112: 6f722069 6e666f72 6d617469 6f6e206f  or infor mation o
  128: 6e206120 73706563 69666963 20636f6d  n a spec ific com
  144: 6d616e64 2e0a0d                      mand...

debug(2) 07:34:52 ts3.c:213 deal_with_ts3_packet() - processing...
debug(3) 07:34:52 ts3.c:227 deal_with_ts3_packet() - packet: combined = 1, challenge = 2, n_servers = 3
debug(2) 07:34:52 ts3.c:262 deal_with_ts3_packet() - combined packet: valid_response: 0, challenge: 2, n_servers: 3, offset: 3
debug(3) 07:34:52 qstat.c:5128 process_func_ret() - 0x85db40, 0
debug(2) 07:34:52 qstat.c:3277 do_work() - connected, post-packet_func: 1
debug(3) 07:34:52 qstat.c:5164 send_packets() - processing...
debug(2) 07:34:52 qstat.c:5207 send_packets() - server 0x85db40, name (null), retry1 3, next_rule (nil), next_player_info 65535, num_players 0, n_retries 3
debug(2) 07:34:52 qstat.c:6246 qserver_get_timeout() - timeout for 0x85db40 is diff1 500 diff2 65535
debug(2) 07:34:52 qstat.c:5283 send_packets() - no queries sent: 0 2000
debug(3) 07:34:52 qstat.c:5300 send_packets() - done
debug(2) 07:34:52 qstat.c:3293 do_work() - connected: 1
debug(2) 07:34:52 qstat.c:6246 qserver_get_timeout() - timeout for 0x85db40 is diff1 1000 diff2 65535
debug(2) 07:34:52 qstat.c:3153 do_work() - rc 1
debug(2) 07:34:52 qstat.c:3181 do_work() - recvfrom: 69
debug(1) 07:34:52 qstat.c:3207 do_work() - recv  50  40 68.3.251.140:10011
debug(2) 07:34:52 qstat.c:3216 do_work() - fill: 1 < 40
FROM servers.bloodbathsoftworks.com:10011 len 69
    0: 6572726f 72206964 3d323536 38206d73  error id =2568 ms
   16: 673d696e 73756666 69636965 6e745c73  g=insuff icient\s
   32: 636c6965 6e745c73 7065726d 69737369  client\s permissi
   48: 6f6e7320 6661696c 65645f70 65726d69  ons fail ed_permi
   64: 643d340a 0d                          d=4..

debug(2) 07:34:52 qstat.c:3275 do_work() - connected, pre-packet_func: 1
debug(2) 07:34:52 ts3.c:213 deal_with_ts3_packet() - processing...
debug(3) 07:34:52 ts3.c:227 deal_with_ts3_packet() - packet: combined = 0, challenge = 2, n_servers = 3
debug(4) 07:34:52 packet_manip.c:187 add_packet() - another packet: 0 id, 2 index, 3 max, 1 calc_max
debug(4) 07:34:52 packet_manip.c:206 add_packet() - calced max = 3
debug(4) 07:34:52 packet_manip.c:42 combine_packets() - max:3, id:0
debug(4) 07:34:52 packet_manip.c:42 combine_packets() - max:3, id:0
debug(4) 07:34:52 packet_manip.c:42 combine_packets() - max:3, id:0
debug(4) 07:34:52 packet_manip.c:143 combine_packets() - callback
FROM servers.bloodbathsoftworks.com:10011 len 220
    0: 5453330a 0d57656c 636f6d65 20746f20  TS3..Wel come to 
   16: 74686520 5465616d 53706561 6b203320  the Team Speak 3 
   32: 53657276 65725175 65727920 696e7465  ServerQu ery inte
   48: 72666163 652c2074 79706520 2268656c  rface, t ype "hel
   64: 70222066 6f722061 206c6973 74206f66  p" for a  list of
   80: 20636f6d 6d616e64 7320616e 64202268   command s and "h
   96: 656c7020 3c636f6d 6d616e64 3e222066  elp <com mand>" f
  112: 6f722069 6e666f72 6d617469 6f6e206f  or infor mation o
  128: 6e206120 73706563 69666963 20636f6d  n a spec ific com
  144: 6d616e64 2e0a0d65 72726f72 2069643d  mand...e rror id=
  160: 32353638 206d7367 3d696e73 75666669  2568 msg =insuffi
  176: 6369656e 745c7363 6c69656e 745c7370  cient\sc lient\sp
  192: 65726d69 7373696f 6e732066 61696c65  ermissio ns faile
  208: 645f7065 726d6964 3d340a0d           d_permid =4..

debug(2) 07:34:52 ts3.c:213 deal_with_ts3_packet() - processing...
debug(3) 07:34:52 ts3.c:227 deal_with_ts3_packet() - packet: combined = 1, challenge = 2, n_servers = 3
debug(2) 07:34:52 ts3.c:262 deal_with_ts3_packet() - combined packet: valid_response: 1, challenge: 2, n_servers: 3, offset: 157
debug(3) 07:34:52 ts3.c:162 send_ts3_request_packet() - send_ts3_request_packet: state = 3
debug(2) 07:34:52 qserver.c:142 send_packet() - [TS3] send
TO servers.bloodbathsoftworks.com:10011 len 6
    0: 71756974 0d0a                        quit..

debug(3) 07:34:52 ts3.c:294 deal_with_ts3_packet() - processing response...
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 0, TS3
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, Welcome
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, to
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, the
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, TeamSpeak
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, 3
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, ServerQuery
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, interface,
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, type
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, "help"
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, for
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, a
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, list
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, of
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, commands
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, and
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, "help
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, <command>"
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, for
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, information
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, on
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, a
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, specific
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, command.
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 1, error
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 2, id=2568
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 2, msg=insufficient\sclient\spermissions
debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 2, failed_permid=4
debug(3) 07:34:52 qstat.c:5128 process_func_ret() - 0x85db40, 2
debug(3) 07:34:52 qstat.c:6144 cleanup_qserver() - cleanup_qserver 0x85db40, 1
debug(3) 07:34:52 qstat.c:6147 cleanup_qserver() - server has no name, forcing close
debug(3) 07:34:52 qstat.c:6170 cleanup_qserver() - close_it 1
servers.bloodbathsoftworks.com:10011 no response
debug(2) 07:34:52 qstat.c:3277 do_work() - connected, post-packet_func: 0
debug(3) 07:34:52 qstat.c:5164 send_packets() - processing...
debug(3) 07:34:52 qstat.c:5300 send_packets() - done
debug(2) 07:34:52 qstat.c:3293 do_work() - connected: 0

The lines from, "debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 0, TS3" to "debug(4) 07:34:52 ts3.c:301 deal_with_ts3_packet() - LINE: 2, failed_permid=4" are particularly interesting because it looks like it tries to login via guest but fails, perhaps I have the wrong username entry for querying as a guest. If anything I'll try again with my TS3 ServerQuery account later today and see what it spits out then.

**Comment by stevenh** [comment]
Yer that's your issue, often query is disabled for guest ;-)

**Comment by Xylemon** [comment]
Well it's rather odd because Guests are allowed to query, but I tried looking into logging into with telnet and turns out I had the wrong login info for the admin the whole time! Now I was able to finally query my TS3 server correctly! Thanks for the help, hopefully I can figure out in the future why qstat isn't querying correctly as a guest.
