### ISSUE TITLE
strndup redefined

### ISSUE THREAD

**Issue by lnussel** [multiplay/qstat#8]
strndup is POSIX.1-2008 therefore nowadays standard on Linux. qstat should not redefine it.

[   17s] In file included from /usr/include/string.h:634:0,
[   17s]                  from qstat.c:31:
[   17s] qstat.c: At top level:
[   17s] qstat.c:12110:7: error: expected identifier or '(' before '__extension__'
[   17s]  char *strndup(const char *string, size_t len)
[   17s]        ^

**Comment by stevenh** [comment]
Fixed https://github.com/multiplay/qstat/commit/9977e09cebc340208ab097f8db619ebc80756859
