### ISSUE TITLE
2.14 or 2.15?

### ISSUE THREAD

**Issue by ilovezfs** [multiplay/qstat#83]
I see a 2.15 tarball in Debian but only a 2.14 tag here. Which is current stable? Where did their tarball come from?

**Comment by akien-mga** [comment]
I think Debian packages a git snapshot as a pre-2.15 release, since there haven't been any release in 5 years.

**Comment by jmallach** [comment]
I don't remember where I got 2.15 from, but if it had been a git snapshot it would be marked as such. However it's been 6 years and I really don't remember anymore. :) Given this, I suggest that if a new release ever happens, it is 2.16, to avoid a versioning mess.

**Comment by stevenh** [comment]
Good point happy accept a PR :)

**Comment by jmallach** [comment]
A PR to cut a release? Ie, release notes etc? I guess I can help with that.

**Comment by jmallach** [comment]
FWIW, 2.16 is out, and I just uploaded it to Debian. This can be closed, I guess.

**Comment by illwieckz** [comment]
On a side note, as seen on [releases page](https://github.com/multiplay/qstat/releases) the `v2.15` tag has an issue, its date is more recent than `v2.16`, that's because the `v2.15` tag commit date is more recent than `v2.16`, despite the date of the tagged commit being older, as we can see:

```
tag v2.15
Tagger: lwaddicor <lewisw@unity3d.com>
Date:   Tue Jul 27 10:54:09 2021 +0100

v2.15

commit 626a5d392fde653c90e491b9e8b22ad6bbac951e (tag: v2.15)
Author: stevenhartland <steven.hartland@multiplay.co.uk>
Date:   Thu Oct 16 10:48:12 2014 +0000

…
```

One can redo the `v2.15` tag and use `--date` option to set the date of the commit being tagged to make it consistent, this way:

```sh
GIT_COMMITTER_DATE='Thu Oct 16 10:48:12 2014 +0000' GIT_COMMITTER_NAME='lwaddicor' GIT_COMMITTER_EMAIL='lewisw@unity3d.com' git tag -f -am 'v2.15' v2.15 626a5d392fde653c90e491b9e8b22ad6bbac951e
```
 
Though, this may look inconsistent between the date and the author. One may prefer to set same date and same author for the tag than for the commit:
 
```sh
GIT_COMMITTER_DATE='Thu Oct 16 10:48:12 2014 +0000' GIT_COMMITTER_NAME='stevenhartland' GIT_COMMITTER_EMAIL='steven.hartland@multiplay.co.uk' git tag -f -am 'v2.15' v2.15 626a5d392fde653c90e491b9e8b22ad6bbac951e
 ```
 
And delete the upstream tag to push this modified one instead.
 
 That `v2.15` tag is retroactive in any case, so better not make it break the various UI.

**Comment by stevenh** [comment]
@lwaddicor can you address @illwieckz request above?

**Comment by lwaddicor** [comment]
Hey, sorry i missed this. Yeah i'll have a look at getting the date on the tag change :+1:

**Comment by lwaddicor** [comment]
I've updated the tag to have the date you suggest. The updated tag has still has my username on it as i felt a bit strange pushing changes as @stevenh, but hopefully it looks good to you now

**Comment by illwieckz** [comment]
On my end I did:

```sh
git tag -d 'v2.15'
git fetch --tags 'https://github.com/multiplay/qstat.git'
git show 'v2.15'
```

and that looks good to me:

```
tag v2.15
Tagger: lwaddicor <****@****.****>
Date:   Thu Oct 16 10:48:12 2014 +0000

v2.15

commit 626a5d392fde653c90e491b9e8b22ad6bbac951e (tag: v2.15)
Author: stevenhartland <****@****.****>
Date:   Thu Oct 16 10:48:12 2014 +0000

    Added KSP support
    
    Bumped version to 2.15
    
    Removed version from .c .h version headers

…
```

It also looks good on https://github.com/multiplay/qstat/releases and https://github.com/multiplay/qstat/releases/tag/v2.15 so everything seems to now be addressed. 🎉

I assume that issue can be closed.

----

_Note:_ now that instructions are applied I now have redacted the various email addresses in my comments.

**Comment by stevenh** [comment]
Thanks all, closing
