### ISSUE TITLE
DarkPlaces games: Support IPv6 (getserversExt + getserversExtResponse) 

### ISSUE THREAD

**Issue by incognico** [multiplay/qstat#84]
DarkPlaces games support IPv6 (Xonotic, OpenArena and more) and the server query protocol does too via getserversExt + getserversExtResponse, see https://github.com/kphillisjr/dpmaster/blob/master/doc/techinfo.txt

Right now when putting the ext commands in the cfg qstat does weird stuff, would be cool to see this supported.

**Comment by stevenh** [comment]
Unfortunately this code base is very much IPv4.

If someone has the time and the inclination to add IPv6 support then we'll definitely consider it, PR welcome 👍

**Comment by stevenh** [comment]
Cleaning up old issues, feel free to reopen if someone wants to add IPv6 support
