### ISSUE TITLE
Configure file missing?

### ISSUE THREAD

**Issue by DanielLeushuis** [multiplay/qstat#87]
Hi,

In the COMPILE.TXT there is an instruction as following:

Linux and other GNU systems
---------------------------
./configure && make

to install qstat run "make install"

to see which configuration parameters can be tweaked, run
"./configure --help"

However, I don't see any configure file except "configure.ac". Am I missing some install steps?

**Comment by gmtandi** [comment]
.ac file means you must build it with autoconf... Check whether there are other files with "auto" or something like that
