### ISSUE TITLE
BFBC2 server text file query

### ISSUE THREAD

**Issue by BETLOG** [multiplay/qstat#91]
How do I query the same IP multiple times with numerous different ports.
eg: (this host:port list)
https://www.gametracker.com/search/bc2/?query=RBL

-noportoffset and -allowserverdups don't seem to be useful... i suspect that there is a port offset required, and the base -default bfbc2 doesn't handle it.

**Comment by stevenh** [comment]
`-f <file>` is the option you want one host per line `<type> <ip>:<port>`

**Comment by BETLOG** [comment]
Maybe you can see what I'm doing wrong:
> BFBC2qstat.sh

`#!/bin/bash
quakestatFile="/home/user/.steamdata/BFBC2serverList.qstat"
frequency=20
tick=$frequency
while :; do
    if [[ $tick -eq $frequency ]];then
        clear
        echo "[$(date +%Y-%m-%d--%H-%M-%S)]"
#        quakestat -nocfg -u -default bfbc2 -nh -ne -f "$quakestatFile"
        quakestat -nocfg -u -nh -ne -f "$quakestatFile"        
        tick=0
    fi
    tick=$((tick+1))    
    sleep 1s
    echo -ne "\\t$(( $frequency-$tick ))\\r"    
done`

>BFBC2serverList.qstat

`bfbc2 125.236.236.79:19568
bfbc2 125.236.236.79:19571
bfbc2 125.236.236.79:19570
bfbc2 125.236.236.79:19567
bfbc2 125.236.236.79:19569
bfbc2 125.236.236.79:19572`

**Comment by stevenh** [comment]
The port when no offset is used must be the query port and not the game port, so that impacts the data you have to specify.

So the question is what are your ports are they query or are they game ports?

**Comment by BETLOG** [comment]
Solved. Gametracker lists the game ports, not the query ports... or something like that.  A standard offset seems to fix it.
```
#!/bin/bash
# betlog - 2019-11-13--11-42-53
#/usr/share/doc/qstat/qstatdoc.html
# 
quakestatFile="/home/user/.steamdata/BFBC2serverList.qstat"
frequency=20
# default base port for BFBC2 -  gametracker.com lists these next to the server IP
portBase=19567
# required to convert game port into query port. ie: 19567+29321=48888
portOffset=29321
# ================
touch /tmp/temp.qstat #didnt work the first time till i did this
tick=$frequency
while :; do
    if [[ $tick -eq $frequency ]];then
        # somone who is familiar with quakestat config syntax should probably convert this awk line into one
        awk -v offset="$portOffset" -v base="$portBase" -F':' \
        '{sum=$2+offset; if(sum==offset)sum=base+offset; print $1":"sum > "/tmp/temp.qstat"}' $quakestatFile
        clear
        echo "[$(date +%Y-%m-%d--%H-%M-%S)]"
        quakestat -nocfg -u -allowserverdups -default bfbc2 -nh -f /tmp/temp.qstat
#         quakestat -nocfg -u -allowserverdups -default bfbc2 -ne -nh -f /tmp/temp.qstat
        tick=0
    fi
    tick=$((tick+1))    
    sleep 1s
    echo -ne "\\t$(( $frequency-$tick )) \\r"    
done
```

```
125.236.236.79
125.236.236.79:19567
125.236.236.79:19568
125.236.236.79:19569
125.236.236.79:19570
125.236.236.79:19571
125.236.236.79:19572
```
