### ISSUE TITLE
Query UT2004 master server, fails to read cdkey windows 10

### ISSUE THREAD

**Issue by serverlinkdev** [multiplay/qstat#96]
Hello,

The documents state:
`qstat -ut2004m,cdkey=/usr/local/games/ut2004/System/cdkey,status=nostandard ut2004master1.epicgames.com:28902`

I'm using:
`qstat.exe -ut2004m,cdkey=D:\\cdkey ut2004master1.epicgames.com:28902
ADDRESS           PLAYERS      MAP   RESPONSE TIME    NAME
debug(0) 20:13:28 ut2004.c:153 send_ut2004master_request_packet() - Error: invalid cdkey parameter
UT2004M ut2004master1.epicgames.com:28902   SYSERROR`

So I'm always falling thru to line 154 of ut2004.c, function:
`query_status_t send_ut2004master_request_packet(struct qserver *server`

I have tried, having the cdkey file as ascii, utf8, with CLRF, w/o CLRF, and linux line endings on windows here as well.  I have also tried having no line endings as well. I've also tried with/without the 'status=' option described in the documentation as well.

I've never been able to get this to work on Windows 1903, or the latest 2004 , home edition.

I *AM* using my patch I submitted in #https://github.com/multiplay/qstat/issues/94 to get this to compile if that makes a difference.  That's the only way to build on windows.

I have verified that Epic's master server is indeed listening for connections.

Thank you in advance for your assistance on this matter.

**Comment by stevenh** [comment]
Sorry for the very slow response, seems I've not been getting notifications of issues for some time.

Try #110 to see if that fixes @serverlinkdev
